### PR TITLE
Update roblox_standard.lua

### PR DESCRIPTION
**Pull request by howmanysmall**
Your luacheck was getting luachecked.

### CODE REVIEW

**Comment by Quenty** [comment]
What Roblox version is this?

**Comment by howmanysmall** [comment]
Same as yours I thought.

**Comment by DarraghGriffin** [comment]
Is this an issue with the generating script? The MakeJoints and BreakJoints fields are duplicated for some reason.

**Comment by Quenty** [comment]
I'm going to just re-generate the result. 

**Edit: ** Will need to reinstall Lua D:

**Comment by Quenty** [comment]
Closing since this is out-of-date

**Pull request closed without merging**
