### PR TITLE
Fixed warning with global instance indexing, and various typos

### PR DESCRIPTION
**Pull request by Nimblz**
These changes fix the issue brought up [here](https://github.com/Quenty/luacheck-roblox/issues/1), along with fixes for a few typos.

### CODE REVIEW

**Comment by Quenty** [comment]
Do we want to set all fields that are read_write as other_fields = true? I’d feel better if we identified instance fields/instances only and set those to be read_write_indexable. 

Would you be able to make this change?

**Comment by Nimblz** [comment]
That's probably a better Idea, I'll make the change!

**Comment by Nimblz** [comment]
messed up commit 941e0f1, force pushed e3a023f.

With these changes assignments like `script.Name.Something = 42` raise a warning as they should! :D

**Review by Quenty — APPROVED** [review]
Approved. Looks good. I've avoided adding `workspace` per Roblox's guidelines, but I think this covers more people's uses, so I'll accept this.

**Comment by Quenty** [comment]
What version of Roblox was this generated on? I want to tag the release with that version.

**Comment by Nimblz** [comment]
I seem to have lost the data directory with the version, you could regenerate the file and release it as todays version

**Comment by Quenty** [comment]
Did it, and added utf8 library! Thank you!

**Pull request merged**
